1.addcslashes() 				返回在指定的字符前添加反斜杠的字符串
2.addslashes() 					返回在预定义的字符前添加反斜杠的字符串
3.bin2hex() 					把ASCII字符的字符串转换为十六进制值
4.chop() 						删除字符串右侧的空白字符或其他字符
5.chr() 						从指定的ASCII值返回字符
6.chunk_split() 				把字符串分割为一系列更小的部分
7.convert_cyr_string() 			把字符串分割为一系列更小的部分
8.convert_uudecode() 			解码uuencode编码字符串
9.count_chars() 				返回有关字符串中所有字符的信息
10.crc32() 						计算字符串32位CRC
11.echo() 						输出一个或多个字符串
12.explode() 					把字符串打散为数组
13.fprintf() 					把格式化的字符串写入指定的输出流
14.get_html_translation_table() 返回由htmlspecialchars()和htmlentities()使用的翻译表
15.hebrev() 					把希伯來文本转换为可见文本
16.hebrevc() 					把希伯來转换为可见文本，并把新行(\n)转换为<br>
17.hex2bin() 					把十六进制值的字符串转换为ASCII字符
18.html_entity_decode() 		把HTML实体转为为字符
19.htmlentities()  				把字符转换为HTML实体
20.htmlspecialchars_decode() 	把一些与定义的HTML实体转换为字符
21.htmlspecialchars() 			把一些与定义的字符转换为HTML实体
22.implode() 					返回由数组元素组合成的字符串
23.join() 						implode()的别名
24.lcfirst() 					把字符串的首字符转换为小写
25.levenshtein() 				返回两个字符串之间的Levenshtein距离
26.localeconv() 				返回本地数字及货币格式信息
27.ltrim() 						移除字符串左侧的空白字符或其他字符
28.md5() 						计算字符串的MD5散列
29.md5_file() 					计算文件的MD5散列
30.metaphone() 					计算字符串的metaphoe键
31.money_format() 				返回格式化为货币字符串的字符串
32.nl_langinfo() 				返回特定的本地信息
33.number_format() 				以千分组来格式化数字
34.ord() 						返回字符串中地一个字符的ASCII值
35.parse_str()  				把查询字符串解析到变量中
36.print() 						输出一个或多个字符串
37.printf() 					输出格式化的字符串
38.quoted_printable_decode() 	把quoted-printable字符串转换为8位字符串
39.quoted_printable_encode() 	把8位字符串转换为quoted-printable
40.quotemeta() 					引用元字符
41.rtrim() 						移除字符串右侧的空白字符或其他字符
42.setlocale() 					设置地区信息(地域信息)
43.sha1() 						计算字符串的SHA-1散列
44.sha1_file() 					计算文件的SH-1散列
45.similar_text() 				计算两个字符串的相似度
46.soundex() 					计算字符串的soundex键
47.sprintf() 					把格式化的字符串写入变量中
48.sscanf() 					根据指定的格式解析来自字符串的输入
49.str_getcsv() 				把CSV字符串解析到数组中
50.str_ireplace()  				替换字符串中的一些字符(对大小写不敏感)
51.str_pad() 					把字符串填充为新的长度
52.str_repeat() 				把字符串重复指定的次数
53.str_replace() 				替换字符串中的一些字符(对大小写敏感)
54.str_rot13() 					对字符串执行ROT13编码
55.str_fhuffle()   				随机打乱字符串中所有字符
56.str_split() 					把字符串分割到数组中
57.str_word_count() 			计算字符串中的单词数
58.strcasecmp()  				比较两个字符串(对大小写不敏感)
59.strchr() 					查找字符串在另一个字符串中的第一次出现(strstr()别名)
60.strcmp()  					比较两个字符串(对大小写敏感)
61.strcoll() 					比较两个字符串(根据本地设置)
62.strcspn() 					返回在找到某些指定字符的任何部分之前，在字符串中查找的字符数
63.strip_tags() 				剥去字符串中的HTML和PHP标签
64.stripcslashes() 				删除由addcslanshes() 函数添加的反斜杠
65.stripslashes() 				删除由addslashes() 函数添加的反斜杠
66.stripos() 					返回字符串在另一个字符中出现的第一次出现的位置(对大小写不敏感)
67.stristr() 					查找字符串在另一个字符串中第一次出现的位置(大小写不敏感)
68.strnatcasecmp() 				使用一种"自然排序"算法来比较两个字符串(对大小写不敏感)
69.strnatcmp() 					使用一种"自然排序"算法来比较两个字符串(对大小写敏感)
70.strncasecmp() 				前n个字符串比较(对大小写不敏感)
71.strncmp() 					前n个字符的字符串比较(对大小写敏感)
72.strpbrk() 					在字符串中查找一组字符的任何一个字符
73.strpos() 					返回字符串在另外一个字符串中第一个出现的位置(对大小写敏感)
74.strrchr() 					查找字符串在另一个字符串中最后一次出现
75.strrev() 					反转字符串
76.strripos() 					查找字符串在另一个字符串中最后一次出现的位置(对大小写不敏感)
77.strrpos() 					查找字符串在另一个字符串中最后一次出现的位置(对大小写敏感)
78.strspn() 					返回在字符串中包含的特定字符数目
79.strstr() 					查找字符串在另一个字符串中出现(对大小写敏感)
80.strtok() 					把字符串分割为更小的字符串
81.strtolower() 				把字符串转换为小写字母
82.strtoupper() 				把字符串转换为大写字母
83.strtr() 						把字符串中特定的字母
84.substr() 					返回字符串的一部分
85.substr_compare()  			从指定的位置开始(二进制安全和选择性区分大小写) 比较两个字符串
86.substr_count() 				计算字串在符号中出现的次数
87.substr_replace() 			把字符串的一部分替换为另一个字符串
88.trim() 						移除字符串两侧的空白字符和其他字符
89.ucfirst() 					把字符串中的首字符转化大写
90.vfprintf() 					把格式化的字符串写到指定的输出流
91.vprintf() 					把格式化字符串写入变量中
92.wordwrap() 					打断字符串为指定数量的字串